# Generated by Django 2.1.8 on 2019-04-19 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(related_name='user_followers_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
