# Generated by Django 2.1.8 on 2019-04-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
