# Generated by Django 2.1.8 on 2019-04-19 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20190419_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment_users',
            field=models.ManyToManyField(related_name='comment_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
